# Generated by Django 3.0.4 on 2020-04-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='Veuillez insérer une image.', upload_to=''),
        ),
    ]
