# Generated by Django 3.0.4 on 2020-04-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200408_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accroche',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
