# Generated by Django 3.0.4 on 2020-04-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_accroche'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auteur',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='accroche',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
